### ISSUE TITLE
your attributes file is terrible

### ISSUE THREAD

**Issue by kplimack** [hw-cookbooks/postgresql#234]
you put so much logic into the attributes file that you've made it very difficult and painstaking to wrap the cookbook.  for example, just to change from version 9.1 to 9.4 on debian, you need ALL of the following config (including where I re-initialize the node[:postgres][:config] hash to {} ).  put ur logic in your recipes and resources, not in the attributes.

```
include_attribute 'postgresql'
default['postgresql']['version'] = '9.4'
default['postgresql']['client']['packages'] = ["postgresql-client-#{node['postgresql']['version']}", "libpq-dev"]
default['postgresql']['server']['packages'] = ["postgresql-#{node['postgresql']['version']}"]
default['postgresql']['contrib']['packages'] = ["postgresql-contrib-#{node['postgresql']['version']}"]
default['postgresql']['dir'] = "/etc/postgresql/#{node['postgresql']['version']}/main"

default['postgresql']['config'] = {}
default['postgresql']['config']['data_directory'] = "/var/lib/postgresql/#{node['postgresql']['version']}/main"
default['postgresql']['config']['hba_file'] = "/etc/postgresql/#{node['postgresql']['version']}/main/pg_hba.conf"
default['postgresql']['config']['ident_file'] = "/etc/postgresql/#{node['postgresql']['version']}/main/pg_ident.conf"
default['postgresql']['config']['external_pid_file'] = "/var/run/postgresql/#{node['postgresql']['version']}-main.pid"
default['postgresql']['config']['listen_addresses'] = 'localhost'
default['postgresql']['config']['port'] = 5432
default['postgresql']['config']['max_connections'] = 100
node['postgresql']['version'].to_f >= 9.3
default['postgresql']['config']['shared_buffers'] = '24MB'
default['postgresql']['config']['max_fsm_pages'] = 153600 if node['postgresql']['version'].to_f < 8.4
default['postgresql']['config']['log_line_prefix'] = '%t '
default['postgresql']['config']['datestyle'] = 'iso, mdy'
default['postgresql']['config']['default_text_search_config'] = 'pg_catalog.english'
default['postgresql']['config']['ssl'] = true
default['postgresql']['config']['ssl_cert_file'] = '/etc/ssl/certs/ssl-cert-snakeoil.pem' if node['postgresql']['version'].to_f >= 9.2
default['postgresql']['config']['ssl_key_file'] = '/etc/ssl/private/ssl-cert-snakeoil.key'if node['postgresql']['version'].to_f >= 9.2
```

**Comment by chrisroberts** [comment]
Hi. This is a completely inappropriate way to create an issue report and not at all constructive or conducive to conversation. There are historical reasons for why these attributes are setup in the format they currently exist and time resources for why a refactor of these attributes has not yet been performed. If you would like to make an attempt to refactor these attributes and their usage, please feel free to fork this cookbook and open a pull request. We are happy to review and respond to issues raised on this cookbook that are polite, or at the very least not condescending. As this issue is neither of those things, I will be closing it.

* https://docs.chef.io/community_guidelines.html
* http://www.catb.org/esr/faqs/smart-questions.html#courtesy
