### ISSUE TITLE
Fails to build pg gem if postgresql::ruby is included

### ISSUE THREAD

**Issue by tpitale** [hw-cookbooks/postgresql#288]
In order to get the pg gem to install I have to disable `postgresql::ruby`, wait for recipe to fail because of missing `pg`. Then, uncomment the `include_recipe` for `postgresql::ruby`, then re-run.

In addition, if I don't have default/override settings in my role for `['postgresql']['client']['packages']`, that errors too because the default recipe hasn't run.

There's also a warning about `compile time false` when I run the ruby recipe.

Using Chef omnibus 12.3.0.

**Comment by nicolasgarnil** [comment]
+1, I have to do the dame
`pg` gem fails to build because, for some reason, `postgresql::ruby` recipe runs before the recipe which installs the `make` package (despite being after in the run list).

**Comment by slyness** [comment]
I discovered that this can happen because currently there were many chances that the node['postgresql']['client']['packages'] where not being installed prior to the attempt to build pg. Which would then fail because of missing dependencies. This will be corrected soon in a 4.0.0 version. See #314 for current work. Branch `dev_4.0.0`.

**Comment by slyness** [comment]
Resolved as of release 4.0.0 - https://github.com/hw-cookbooks/postgresql/releases/tag/v4.0.0
